version: "3.9"

services:
  java:
    build: .
    container_name: finalProjectSQLHibernate
    depends_on:
      - mysql_db
      - cache
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: world
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql/
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
